### ISSUE TITLE
Theme Check issues

### ISSUE THREAD

**Issue by andrejarh** [CMB2/CMB2#1050]
While doing a standard testing procedure for ThemeForest,  I noticed following errors,
using [the themecheck plugin](https://wordpress.org/plugins/theme-check/):

**add_theme_page:**
REQUIRED: framework/meta/CMB2/includes/CMB2_Options_Hookup.php. Themes should use add_theme_page() for adding admin pages.
Line 93: $page_hook = add_menu_page(
REQUIRED: framework/meta/CMB2/includes/CMB2_Options_Hookup.php. Themes should use add_theme_page() for adding admin pages.
Line 84: $page_hook = add_submenu_page(

**TRANSLATIONS:**
(This are small and easy fixes, just add "CMB2" as the second argument)
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Toggle panel: %s'
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'The register_routes() method must be overridden'
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Scope under which the request is made; determines fields present in response.'
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Maximum number of items to be returned in result set.'
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Limit results to those matching a string.'
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Current page of the collection.'
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments "Method '%s' not implemented. Must be overridden in subclass."

**Comment by jtsternberg** [comment]
The `add_theme_page` bit is not helpful. That is specific to themes, but CMB2 can be used for many kinds of projects, and options pages be added to any menu item.

The translations are all strings that live in WordPress, and therefore, we are depending on the WordPress translation files to kick in instead of requiring our much more limited set of translation files to be used.

If you Theme Check has a repo, you may want to open an issue there with these details.

**Comment by andrejarh** [comment]
Hi, 
Thanks for reply,
**1st point: add_theme_page**
This issues might violate the themeforest coding guidlines if included in themes, ThemeForest themes won't be able to use your wonderful project, because they might be rejected by the ThemeForest reviewers. They seem to be very strict on this.

**2st point: translations**
I think you misunderstand the issue here. Function __ is used for translations. All examples in previous issue are from your codebase.  For example, the first one:
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Toggle panel: %s'

This is from your CMB2_hookup class in /includes/CMB2_hookup.php file, line 458. It reads:

`echo '<span class="screen-reader-text">' . sprintf( __( 'Toggle panel: %s' ), $title ) . '</span>';`
The proper way to use __ function is:
`__( 'Toggle panel: %s', 'cmb2' );` (just add your textdomain as second argument and it'll be fine).
Here is the codex page: [https://codex.wordpress.org/I18n_for_WordPress_Developers](https://codex.wordpress.org/I18n_for_WordPress_Developers).

I also want to warn you against abusing translation files to execute malicious code. Use esc_html__  or esc_attr__ instead of __ wherever possible. More info on escaping here:
[https://codex.wordpress.org/Data_Validation#Text_Nodes](https://codex.wordpress.org/Data_Validation#Text_Nodes)

I am sorry to be a bugger, I really like CMB2 project. You've done a wonderful job on it. I only reported this to help.

Cheers!

**Comment by jtsternberg** [comment]
If we limit CMB2 to only use add_theme_page, then it will severely limit the usefulness of the tool. Again, this probably should be brought up with themeforest or the theme checker.

Re: translations, I completely understand. Perhaps reviewing [this stackoverflow answer](https://wordpress.stackexchange.com/a/196460/45740) will help explain. The strings in question are all strings that are used in WordPress core. I am very intentionally NOT adding the `'cmb'` text-domain, because I do not want it to use CMB2 plugin translations, but the WordPress core translations instead.

Re: `esc_html__()` and `esc_attr__`, I will be happy to look at a pull request if you are up for it.

**Comment by tw2113** [comment]
Justin, i know it may be a little bit of visual noise, but perhaps in spots where we purposely don't provide the text domain, we can add a note regarding why.

**Comment by jtsternberg** [comment]
@tw2113 I assume you mean in the codebase, via documentation? If so, I'd be happy to look at a pull request if you're up for it.

**Comment by tw2113** [comment]
Yeah, just some inline comments for the spots.
