### ISSUE TITLE
Options page > type 'fill' (image) 

### ISSUE THREAD

**Issue by dhenriet** [CMB2/CMB2#1086]
If an image has been uploaded, if you save, image disappears.

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1. Upload image
2. Select uploaded image
3. Save
4. Save again 

### CMB2 Field Registration Code:
https://gist.github.com/dhenriet/4139afaf7f2845fcf5e840c59aeb0017

### Select image
![screenshot_6](https://user-images.githubusercontent.com/4640027/35474565-4473184e-0390-11e8-8645-ae42221da85a.png)

### Save
![screenshot_7](https://user-images.githubusercontent.com/4640027/35474547-0db17148-0390-11e8-9cba-1a384e7c2fd3.png)

### Save again
![screenshot_8](https://user-images.githubusercontent.com/4640027/35474548-0dd12e16-0390-11e8-92d9-ed056e0e105b.png)

**Comment by tw2113** [comment]
Not managing to recreate myself at the moment. Both fields keep showing the previews no matter how many times I hit save.

What version of CMB2 are you on?

**Comment by MWDavidH** [comment]
Hi, thanks for your answer ! Sorry it's a local configuration problem. My CMB2 version is 2.3.0 and wordpress 4.9.2.
After inspecting with F12, I found the problem. The image is here but I can't see it because the upload path is wrong. I am working with "browserSync" so my local url is "//localhost:3000/my-project/, when I press save the path changes to `src="//localhost:3000:3000/my-project/wp-content/uploads/`. The path shoud be `//localhost:3000/my-project/wp-content/uploads/`.

**Comment by tw2113** [comment]
Ah, interesting. Not sure how best to help handle that part, but it definitely sounds like not something we can address with the plugin itself.
