### ISSUE TITLE
Save post meta under one key

### ISSUE THREAD

**Issue by shakeeb-mts** [CMB2/CMB2#1120]
Hi,

The default way of CMB2 to save post meta is under different keys. I want to save all the options as 1 key same as the CMB2_Options is doing.

Thanks

**Comment by tw2113** [comment]
Creating a field group should save all the items under 1 key.

https://github.com/CMB2/CMB2/wiki/Field-Types#group

Closing as not an issue with the library, but you can still comment after closing :)

**Comment by shakeeb-mts** [comment]
@tw2113 but the UI will not look cools and also I want to categorize data in tabs, how to achieve this.

**Comment by tw2113** [comment]
Best answer i have for all those "why's" question is probably because no one has extended in that way thus far, that ended up merged into CMB2 core. They may have their own implementations that are elsewhere.

Regarding alternative ways to save data, it is possible to intercept during the save process and store it however which way you may want. I can't recall the hooks offhand but can track them down if needed
