### ISSUE TITLE
Custom MetaBox - Get all users (selector)

### ISSUE THREAD

**Issue by Msantanna10** [CMB2/CMB2#1152]
Hello! I've been trying to get it solved for ages! All I want is a selector where I can choose some specific users (or only one), I haven't seen any custom metabox box that does so, I've seen a selector that selects existing pages/posts but nothing about users. I tried something like that but nothing so far, how could I accomplish that?

```
$fields = array(
	array(
		'id'   => 'user_selector',
		'name' => 'Select an user',
		'type' => 'select',
		'ajax' => 'true',
			'query' => get_users()
	)	
);	

$meta_boxes[] = array(
	'title'   => 'Selector',
	'pages'   => 'page',
	'fields'  => $fields,
);
```

**Comment by tw2113** [comment]
Couple things.

1. It looks like you're using the old style for adding metaboxes. You should really update what you're trying with to use `new_cmb2_box(). Check the wiki for current examples.

2. You're going to want to define some arguments to use for `get_users()` and create a key/value array to be used for the select options, instead of just trying to pass in the results. Perhaps store the user ID as the array key, and the array value being the display name.

**Comment by tw2113** [comment]
Any news or followup with this one @Msantanna10 ?
