### ISSUE TITLE
repeater field adds new row on each save

### ISSUE THREAD

**Issue by cannap** [CMB2/CMB2#1153]
### Expected Behavior:
Repeater field should stay sync with the current ui

### Actual Behavior:
https://www.useloom.com/share/8ee80a0b4c8045c8bde15d59e686c002

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1. Save The post
2. Repeater adds new field

### CMB2 Field Registration Code:

```php

		$cmb_for_worker_job->add_field( [
		'name'       => 'Bundesländer',
		'id'         => $prefix_job . 'states',
		'repeatable' => true,
		'type'       => 'select',
		'default'    => 'some-more',
		'options'    => [
		'BW' => 'Baden-Württemberg',
		'BY' => 'Bayern',
		'BE' => 'Berlin',
		'BB' => 'Brandenburg',
		'HB' => 'Bremen',
		'HH' => 'Hamburg',
		'HE' => 'Hessen',
		'MV' => 'Mecklenburg-Vorpommern',
		'NI' => 'Niedersachsen',
		'NW' => 'Nordrhein-Westfalen',
		'RP' => 'Rheinland-Pfalz',
		'SL' => 'Saarland',
		'SN' => 'Sachsen',
		'ST' => 'Sachsen-Anhalt',
		'SH' => 'Schleswig-Holstein',
		'TH' => 'Thüringen',
	]
	] );
}
```

Current workaround: 

```php
	'sanitization_cb' => function ( $value ) {
			return array_unique( $value );
		},
```

**Comment by tw2113** [comment]
Can you also provide the entirety of your CMB2 config, instead of just the one `$cmb_for_worker_job->add_field( ... )` ?

**Comment by tw2113** [comment]
Definitely managing to recreate it at the moment, using the full code, and mixing in the previously listed out states, instead of using `get_german_states()`

Regarding the hidden row part, I believe that's how CMB2 handles the repeatable aspect and adding a new field row. I would need to confirm with @jtsternberg though.

Regarding the incrementing on save part, I believe it's purposely adding thr new row visually, in prep for the user adding more. However, due to not having an empty value that would prevent adding a new selection to the list during save, it ends up saving the first one listed. This repeats. Once I added `'show_option_none' => true,` to the field, it has thus far stopped repeating itself.

Ultimately, my suggestion is to use the show_option_none or provide an empty value in your states listing, and see if that solves all your issues.
