### ISSUE TITLE
Packagist needs to be updated to CMB2 as a company instead of WebDevStudios

### ISSUE THREAD

**Issue by tw2113** [CMB2/CMB2#1180]
https://packagist.org/packages/webdevstudios/cmb2

**Comment by jtsternberg** [comment]
From what I can tell, packagist doesn't allow changing that.

**Comment by tw2113** [comment]
Alternative method, create a new user account and do the routine over again?

**Comment by jtsternberg** [comment]
This is the bummer solution: https://github.com/composer/packagist/issues/47

**Comment by earthyah** [comment]
So this does work

**Comment by earthyah** [comment]
Does or doesnt? Sorry

**Comment by jtsternberg** [comment]
Since we [can't keep download stats](https://github.com/composer/packagist/issues/47#issue-1923500), I'll keep a screenshot of them here for posterity. 

<img width="1428" alt="screen shot 2018-10-22 at 1 25 14 pm" src="https://user-images.githubusercontent.com/1098900/47307861-15dcc700-d5fe-11e8-8c62-6135683d6f89.png">

|   |  |
| ------------- | ------------- |
| [Installs](https://packagist.org/packages/cmb2/cmb2/stats) | 74,823 |
| [Dependents](https://packagist.org/packages/cmb2/cmb2/dependents) | 8 17 |
| [Suggesters](https://packagist.org/packages/cmb2/cmb2/suggesters) | 0 |
| [Stars](https://github.com/CMB2/CMB2/stargazers) | 2,113 |
| [Watchers](https://github.com/CMB2/CMB2/watchers) | 175 |
| [Forks](https://github.com/CMB2/CMB2/network) | 488 |
| [Open Issues](https://github.com/CMB2/CMB2/issues) | 199 |
| Type | wordpress-plugin|

**Comment by slaFFik** [comment]
I believe, this issue could be closed?
