### ISSUE TITLE
Metabox fields in registration form doesn't work.

### ISSUE THREAD

**Issue by developerpaddy** [CMB2/CMB2#1183]
Hey Guys,

Thanks for the great work, this inspires me to do some custom work in WordPress.

Right now I am struggling with adding metabox fields to WordPress registration form,
I have achieved it at some extent. Where I am stuck is I have managed to add the fields and save the data from registration form to custom fields created with CMB2.

In my form I have Date and time field which not working as expected. When I diagnosed this issue I found,
1. jQuery is not enqueueing at registration page.
2. Also I think dependency is also not their (datepicker div/calender popup and time select popup).
3. when i output the same in other front pages it works as expected but not on Registration page.en this 

If it get solved then this will be great opportunity to create registration form with metabox fields.

Thanking You in advance. Please help me.

**Comment by tw2113** [comment]
Last I was aware or had seen, we don't have any official, tested, support for adding fields to the registration form. We do have user profile support but that's after they have already been registered and set up.

To be certain, the registration page you're referring to is the one seen at wp-login.php with some extra $_GET arguments to indicate they're signing up for a new user, correct? Or perhaps some custom registration page that a different plugin created like BuddyPress or WooCommerce?

Extra thoughts: when in doubt, you can always enqueue your own js/css files, just a matter of finding the correct hook to do it on. Frontend is `wp_enqueue_scripts`, admin is `admin_enqueue_scripts`, and wp-login.php based pages are `login_enqueue_scripts`.

If it was a custom registration page, like the BuddyPress or WooCommerce one, I believe things would generally just work, or potentially would, as opposed to wp-login.php version. This would be because the scripts and hooks are already set to be run.

**Comment by developerpaddy** [comment]
Hey thanks bro,

I was tried `login_enqueue_script` and and enqueued some script but yes you are right, rather than playing around wp-login.php we can develop custom login and registration flow and custom pages for the same.

I will try by this route.
thanks for your reply, and god bless you guys you are doing great work.

**Comment by tw2113** [comment]
Welcome.
