### ISSUE TITLE
cmb2_get_option Value displays three times

### ISSUE THREAD

**Issue by broros** [CMB2/CMB2#1232]
string(10) "1234567890" string(10) "1234567890" string(10) "1234567890"

```
add_action( 'cmb2_init', 'wp_api_slug' );   
function wp_api_slug(){
	add_filter( 'rest_url_prefix', 'api_slug');
}

function api_slug( $slug ) {
	$wp_rest_url = cmb2_get_option('wp_secondary_options', 'wp_rest_textmedium');
	var_dump( $wp_rest_url);
	// if (!empty($wp_rest_url)) { 
	// return $wp_rest_url;
	// }
}
```

**Comment by tw2113** [comment]
Before trying to use it, what all is stored in your `wp_secondary_options`.

Whats your entire CMB2 config so we can potentially set up in our local install and attempt to recreate?

**Comment by broros** [comment]
```
$secondary_options = new_cmb2_box( array(
		'id'           => 'wp_secondary_options_page',
		'title'        => esc_html__( 'Options', 'cmb2' ),
		'object_types' => array( 'options-page' ),
		'option_key'   => 'wp_secondary_options',
		'parent_slug'  => 'wp_main_options',
	) );
```

**Comment by tw2113** [comment]
Is there any specific reason you're using the `cmb2_init` hook to add your callback? It's generally been my experience that for some reason, `init`, which `cmb2_init` is tied to, runs a handful of times, which would explain why you get 3 echos of your value. If there's a different hook that you can use, may be better to use that one.

**Comment by broros** [comment]
all I want to do is change the rest api url prefix, Which hook should I use?

**Comment by tw2113** [comment]
Instead of wrapping the add filter in a different action callback, I'd just use this below directly, right in your functions.php file. I copy/pasted exactly, I trust you'll clean up the api_slug function to best fit needs in the end.

```
function api_slug( $slug ) {
	$wp_rest_url = cmb2_get_option('wp_secondary_options', 'wp_rest_textmedium');
	echo $wp_rest_url;
	// if (!empty($wp_rest_url)) { 
	// return $wp_rest_url;
	// }
}
add_filter( 'rest_url_prefix', 'api_slug');
```

**Comment by broros** [comment]
If I do that I get

`Fatal error: Uncaught Error: Call to undefined function cmb2_get_option() in ...`

**Comment by tw2113** [comment]
where are you defining that one? plugin? theme files?

may need to go back to the wrapping of the line above, but perhaps use `plugins_loaded` or `after_setup_theme` hooks instead of init. Alternatively, you could deconstruct what is in `cmb2_get_option()` and just see how exactly it's fetching specific values from the overall saved option serialized data. `cmb2_get_option()` is just a fancy helper function, really.

**Comment by broros** [comment]
I tried it in both theme and plugin with same results

**Comment by tw2113** [comment]
Brings me back to my question of where' you're putting your copy of `cmb2_get_option()` to be defined.

**Comment by broros** [comment]
the problem is that cmb2_get_option() cannot be called outside of the cmp2 loop...

**Comment by broros** [comment]
cmb2_get_option() ONLY works inside -> add_action( 'cmb2_init')

**Comment by tw2113** [comment]
Apologies, I was thinking you were using something like https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php#L63-L88 which isn't actually the case. This is also why i was talking about where you're defining things and "checking out the internal of it".

That said, maybe dropping in your own copy of that function would help out in your case. It'll check if the function exists and if so, utilize it, otherwise it'll pluck things out of the database with WP standard get_option().

Some extra notes to keep track of things. `cmb2_get_option()` is defined in the helper-functions.php file, and that one is not run until the init hook. So that part is making sense. There also may be promise in `cmb2_after_init` hook, but I can't say for certain in this case.

**Comment by broros** [comment]
cmb2_after_init  is the same as cmb2_init,  I'm still getting three values printed on the page

this will print out one value:

add_action( 'cmb2_init', 'wp_api_slug' );   
function wp_api_slug(){
	$wp_rest_url = cmb2_get_option('wp_secondary_options', 'wp_rest_textmedium');
	echo $wp_rest_url;
}

and what I have on at the first comment above will print three values, Do you know why this is happening?

**Comment by tw2113** [comment]
Because init gets fired a number of times. Pretty sure the AJAX stuff triggers it as well as just a simple pageload.

Let's go with the snippet I pointed out in my last reply, and run with that for your needs.

**Comment by broros** [comment]
my conclusion is that there is something wrong with CMB2, the code below should work perfectly fine except that it gives me three values instead of one.

```
add_action( 'admin_init', function() {
  add_filter( 'rest_url_prefix', function($slug) {
   $wp_rest_url = cmb2_get_option('wp_secondary_options', 'wp_rest_textmedium');
	echo $wp_rest_url;
  } );
} );
```

**Comment by tw2113** [comment]
Not trying to be combative here, but just trying to narrow things down and figure things out with you.

1. I don't think testing echo'd output on these hooks is very indicative of anything. What are we trying to test with it?
2. I still have the rest_url_prefix hook parts in place in my local. I put a breakpoint in it, and the breakpoint caught 3-4 times, this is because, as I found, the function that filters the prefix value is called that many times for a pageload.
3. I added an echo statement outside of that callback for rest_url_prefix, but still inside the cmb2_init callback, and it only echo'd once.
4. I added an echo statement for a callback on just init, and that only output once.

So, the amount of times things are echo'd isn't really telling us anything other than the filter is used many times in the pageload.

Now. I have the following snippet in a file in a mu-plugin folder, and I'm not managing to get any errors from it. mu-plugins run pretty early in the loading chain, so the filters global array is getting populated early. I do have the standalone CMB2 plugin active, it's not part of a theme or bundled with a different plugin. Not sure where your copy is at in your site.

```
add_action( 'cmb2_init', 'wp_api_slug' );
function wp_api_slug() {
	add_filter( 'rest_url_prefix', 'api_slug' );
}

function api_slug( $slug ) {
	$wp_rest_url = cmb2_get_option( 'wp_secondary_options', 'wp_rest_textmedium' );
	return $wp_rest_url;
}
```

My saved value for that option is "avc". Attached is a screenshot of the 3 times that it is showing up for me
![screen shot 2019-03-06 at 6 09 09 pm](https://user-images.githubusercontent.com/484075/53922698-07d29480-403b-11e9-96e7-e9c8bc9aca1d.png)

So, either, somehow your code is running too early before cmb2_get_option is loaded, or something else is going on. In terms of the fatal errors, I'm not experiencing any with the intended goal.

**Comment by broros** [comment]
I understand what you are saying, it will only change in the source code but not in the url ( you have to update your permalinks )
if you try " /avc/wp/v2  " you will get an error

**Comment by tw2113** [comment]
I could see needing to flush permalinks, but that all is going to be more a WP core issue than a CMB2 one at this point. So many details

**Comment by broros** [comment]
I think rest_url_prefix filter runs very early,

**Comment by jtsternberg** [comment]
Don't bother using `cmb2_get_option`. It's only there for convenience, but when you need to run code as early as you are (before `init`), then you can't depend on the CMB2 functions. You can simply do something like this:
```php
add_filter( 'rest_url_prefix', 'yourprefix_api_slug' );
function yourprefix_api_slug( $slug ) {
	$options = get_option( 'wp_secondary_options', [] );
	if ( ! empty( $options['wp_rest_textmedium'] ) ) {
		$slug = $options['wp_rest_textmedium'];
	}
	
	return $slug;
}
```

**Comment by jtsternberg** [comment]
I'm closing this as it's not a CMB2 issue, though you can continue to comment if needed. Next time, please do not disregard the Issue template questions, as it provides us with a lot of helpful context as to how we can help you.
