### ISSUE TITLE
Native Wordpress revision support

### ISSUE THREAD

**Issue by orvn** [CMB2/CMB2#1253]
Wordpress' native version control is a useful feature, and as far as I can tell, CMB2 does not support it.

i.e., if I have a set of metaboxes added to a page template, and a page assigned to that template, the revisions of each field are not available (unless there's something incorrect about my implementation).

As a potential new feature, all the fields could be concatenated, wrapped in special comments that indicate each metabox name and populated when restoring revisions.

Has this kind of feature request been considered? (unable to find a similar one in search)

**Comment by tw2113** [comment]
Wouldn't this topic trickle down into WordPress core not even handling meta with revisions? Or has that since been addressed/resolved?

**Comment by salcode** [comment]
I agree WordPress's native version control is a cool feature but @tw2113 is correct that currently version control applies to the post content only (not the post meta where CMB2 stores its values).

There is a WordPress track ticket, [ticket 20564](https://core.trac.wordpress.org/ticket/20564) *Framework for storing revisions of Post Meta*, about adding this functionality to WordPress core in the future.

Associated with the WordPress ticket there is also a plugin [WP-Post-Meta-Revisions](https://github.com/adamsilverstein/wp-post-meta-revisions) where they are trying out the idea of storing post meta revisions.

@orvn, since post meta revisions isn't part of WordPress core currently (but hopefully will be in the future), I'm going to close this issue. Feel free to re-open if you think this needs more attention at this time.

Thanks.
