### ISSUE TITLE
CMB2 Boxes in modal attachment windows

### ISSUE THREAD

**Issue by Fiorinol** [CMB2/CMB2#1273]
In the media library, it is possible to change the fields of an attachment using the modal windows in grid view. However, CMB2 boxes don't appear in the modal window fields. I need to go down to "Edit more details" to go on the post's edit page to be able to edit those fields. Here is a rudimentary cmb2 box:

```
add_action( 'cmb2_admin_init', 'media_registration');

function media_registration(){
	$media = new_cmb2_box( array(
		'id'           => 'cmb2_attachment_credit',
		'title'        => 'Image Credit',
		'object_types' => array( 'attachment' ),
		'context'      => 'normal',
		'priority'     => 'high',
		'show_names'   => true,
	));

	$media->add_field( array(
		'name' => 'Author Name',
		'desc' => 'The full name of the person who contributed this piece.',
		'id'   => 'cmb2_attachment_name',
		'type' => 'text',
	));
}

```

If I add a field using the attachment_fields_to_edit filter ( https://www.ibenic.com/extending-wordpress-media-uploader-custom-fields/ ). The fields appear in both the modal window and the post's edit page. I could probably use the API to bring up the fields in the modal window, but it seems like an oversight when I can add fields to attachments already, and I'm not sure how I would go about it.

**Comment by tw2113** [comment]
Just wanted to drop in some early thoughts. This is definitely on the side of a feature result, and could be considered a not-as-developed-as-could-be thing.

The reasons for that are that the media modal is not the same as a metabox, so the interaction and UI are completely different. Because of that, different strategies would be needed to integrate more in there, especially in the areas of backbone and javascript.

**Comment by Fiorinol** [comment]
I see. I thought I was doing something wrong on my end or that one of the many 3rd party resources would provide a solution. I will probably use attachment_fields_to_edit for the time being.
