### ISSUE TITLE
Multiples warnings on repeatable color picker

### ISSUE THREAD

**Issue by rubengc** [CMB2/CMB2#1285]
Hi there

I just found multiples PHP warnings when setting up a `colorpicker` field as `repeatable` and passing as `default` parameter an array

The fields get displayed correctly and initializes correctly with the values you setup, but this configuration causes a set of warnings all of them on class `CMB2_Type_Colorpicker`

2 errors "preg_match() expects parameter 2 to be string, array given" on CMB2_Type_Colorpicker lines 39 and 44
1 error "trim() expects parameter 1 to be string, array given" on CMB2_Type_Colorpicker line 46

Hope it helps to continue improving CMB2

Best regards

**Comment by tw2113** [comment]
For repeatability sake, can you provide what you're using for your fields/field args?

**Comment by rubengc** [comment]
Hi @tw2113 

Yes of course, there is the field setup:
```
add_action( 'cmb2_admin_init', 'cmb2_custom_metabox' );
function cmb2_custom_metabox() {
	$prefix = 'your_prefix_demo_';

	$cmb_demo = new_cmb2_box( array(
		'id'            => $prefix . 'metabox',
		'title'         => __( 'Field Sample', 'cmb2' ),
		'object_types'  => array( 'page', 'post' ), // Post type
	) );

	$cmb_demo->add_field( array(
		'name'         => __( 'Test', 'cmb2' ),
		 'type'          => 'colorpicker',
		'options'       => array( 'alpha' => true ),
		'repeatable' => true,
		'default'       => array('#000','#555','#999'),
	) );
}
```

**Comment by tw2113** [comment]
@rubengc Biggest thing standing out to me, right away, is your default line: `'default' => array('#000','#555','#999'),`. Does it claim somewhere that this takes an array? Otherwise I think that should be just a string with 1 value.

If you set that to just black, for example, do the errors go away?

**Comment by rubengc** [comment]
Hi @tw2113 

Of course, setting it to a string no error happens

But, I was used this way of use array of default values on repeatable fields to initialize fields with a set of predefined options (which is an awesome feature)

All fields was working correctly and the unique with php warnings was the colorpicker field

So, why not fix this issue and keep the ability to pass array default values for repeatables?

**Comment by rubengc** [comment]
Ah @tw2113 

I found where issue happens

On repeatable fields, CMB2 generates an "empty" one to be used as pattern for new fields

This "empty" field is the unique that receives the array default value

**Comment by tw2113** [comment]
If you're suggesting we make it possible to pass an array of default values as part of using the field type in a repeatable group, then that's a topic that should get a new issue here in GH so that we can evaluate and consider.

That said, regarding the warnings/errors as is, it still only takes a string value. So this specific issue, #1285, would be invalid until that array value is accepted.

**Comment by rubengc** [comment]
Ok @tw2113 I just started the proposal topic on #1286
