### ISSUE TITLE
How to set a min and max limit for taxonomy_multicheck type?

### ISSUE THREAD

**Issue by sebastillar** [CMB2/CMB2#1288]
In my project, the users must to select between 3 and 5 tags when create a new post. I am using taxonomy_multicheck type.

`	$cmb_custom->add_field( array(
		'id'       => $prefix . 'multitaxonomy',		
		'name'     => __( 'Tags Emoción', 'cmb2' ),
		'desc'     => __( 'Seleccione entre 3 y 5 tags.', 'cmb2' ),
		'type'     => 'taxonomy_multicheck',
		'taxonomy' => 'emocion', // Taxonomy Slug
		'inline'  => true, // Toggles display to inline
	) );`

How could I define the user to select between 3 and 5 of them?

Thank you!

Thanks!

**Comment by tw2113** [comment]
Because i'm still a bit "on" before the weekend.

This is going to likely be something custom, as I do not believe we have anything available for this in CMB2 core, and there's not really `minlength` and `maxlength` attributes for HTML checkboxes.

Perhaps resources at either of these may inspire? They both mention the max amount, so you'd need to amend to include minimum amounts as well

https://www.roytuts.com/limit-number-of-checkbox-selections-using-javascript/
https://stackoverflow.com/questions/19001844/how-to-limit-the-number-of-selected-checkboxes
