### ISSUE TITLE
Select options additional information

### ISSUE THREAD

**Issue by criting** [CMB2/CMB2#1289]
Isn't there really a way to add something to the action options of an select input? Like data attribute or class.. that's one of the most common practices for selects, am I missing something? Because I see it as impossible to do it with CMB2.

**Comment by slaFFik** [comment]
Hi @criting 

You can add custom attributes (any, including `data-`) like this ([see docs](https://github.com/CMB2/CMB2/wiki/Field-Parameters#attributes)):
```php
$cmb->add_field( array(
    'name'        => 'Extra Small Textarea',
    'id'          => 'wiki_test_xtra_small_textarea',
    'type'        => 'textarea_small',
    'attributes'  => array(
        'placeholder' => 'A small amount of text',
        'rows'        => 3,
        'required'    => 'required',
    ),
) );
```

For classes, you can use this [built-in solution](https://github.com/CMB2/CMB2/wiki/Field-Parameters#classes).

**Comment by criting** [comment]
This doesn't work for select options, I'm trying to add different data attribute for each option.

**Comment by criting** [comment]
I don't know how you closed the issue since your answer isn't relevant to my question at all...

**Comment by slaFFik** [comment]
Oh, sorry, you actually meant `options` for `select` field type.
Technically, there 2 ways to do that.

1) Longer:
Instead of using default class `CMB2_Type_Select` for `select` field type, extend it like this: `class Your_CMB2_Type_Select extends CMB2_Type_Select {}` - and copy all content from `CMB2_Type_Select` to your class, plus add a way to pass custom attributes for options.
In your class redefine this method from the abstract `CMB2_Type_Multi_Base` class:
```php
	/**
	 * Generates html for an option element
	 *
	 * @since  1.1.0
	 * @param  array $args Arguments array containing value, label, and checked boolean
	 * @return string       Generated option element html
	 */
	public function select_option( $args = array() ) {
		return sprintf( "\t" . '<option value="%s" %s>%s</option>', $args['value'], selected( isset( $args['checked'] ) && $args['checked'], true, false ), $args['label'] ) . "\n";
	}
```
with ability to apply custom attributes passed to this method through `$args` variable that is passed from your class to `CMB2_Type_Multi_Base::concat_items()` and from there to your `Your_CMB2_Type_Select::select_option()`.
Register this as a new field type, `selected_enhanced_options` - and use it in your code.

2) Try to use `"cmb2_{$element}_attributes"` (defined in `\CMB2_Type_Base::parse_args()` filter as `cmb2_select_attributes`, all options will be already generated there with all HTML, so you will need to use `preg_replace()` or `str_replace()` to change `<option value=` to something like `<option data-customId="{$custom_id}" value=`.

I hope that helps.

**Comment by slaFFik** [comment]
Oh, found an easier solution, you can copy-paste with certain modifications [this snippet](https://github.com/CMB2/CMB2-Snippet-Library/blob/master/custom-field-types/select-multiple-field-type.php). On line 26 there is generates options, you can reuse any field parameters there from `$field` variable.

**Comment by tw2113** [comment]
Let us know if slFFik's suggestions help cover your usecase for data attributes on the options for the select field. In terms of the `<select>` tag itself, the `attributes` parameter is a valid way to get some extra parts on it, like a custom class if needed. However it doesn't apply to the options themselves, as already noted.
