### ISSUE TITLE
Arrange files from a file_list metabox alphabetically in dashboard

### ISSUE THREAD

**Issue by roscabgdn** [CMB2/CMB2#1341]
**Is your feature request related to a problem? Please describe.**
I want to arrange alphabetically images that I upload in a field_list meta.

**Describe the solution you'd like**
When I create the metabox in php file somehow to have the posibility to set how the files
should be arranged in the admin/frontend.

**Describe alternatives you've considered**
Maybe a filter in the field_list (like a dropdown) in order to arrange them by date, name etc.

**Additional context**
I add a lot of images and it would be nice to have them arranged alphabetically.

**Comment by tw2113** [comment]
I could see this being potentially meticulous and difficult to get right, depending on which aspect of the value you want sorted by. 

For example:

```
http://www.site.com/wp-content/uploads/2027/02/xyz.png
http://www.site.com/wp-content/uploads/2020/02/some-image.jpg
http://www.site.com/wp-content/plugins/thing/graphic.gif
http://www.site.com/wp-content/oops.jpg
http://www.site.com/wp-content/themes/me/img/file.png
http://www.site.com/wp-content/plugins/thing4/image.png
http://www.site.com/wp-content/uploads/2009/08/large-image.jpg
```

This list would first be alphabetically sorted by the first unique characters after the trailing slash on wp-content. Then so on and so on as the next unique characters get found, so the 2027 year folder would get put after the 2009 and 2020 ones. One may or may not want that, and instead just want organized by file name. Who's to say?

That said, and if you're interested in this one, I know we have hooks that are run both before display, and before save, that you could probably use to intercept the data and just do some sort of sorting code functions on. That way you would be able to sort them automatically before saving, or before display. I'd probably lean towards before saving personally, so that it doesn't need to be run every single time. this would be UI-less though which is part of your original idea here.

**Comment by roscabgdn** [comment]
I will look into that. Yeh definitely the before saving hook is the one I want to use. Can you please tell me what that hook is called and where I can find IT? 

Thank you!

**Comment by tw2113** [comment]
Agh, i was partially right, but also partially mistaken. We do have filters in the retrieval/updating process, but they're meant to allow for intercepting and manually processing the data in some other way. For example if you wanted to store in a custom table, but don't want to worry about creating your own functions to retrieve that data, favoring get_post_meta etc instead.

In terms of the saving part, there is https://github.com/CMB2/CMB2/blob/develop/includes/CMB2_Field.php#L321-L355

Wouldn't be the worst thing to just manually sort and then run all the parts through the appropriate update_post_meta() calls on your own and then return a non-null value so that you don't immediately overwrite the same keys with the original data.

The second filter offers the ability to do it for only specific fields, and can spare some early return checks for fields you don't need this for.

Sorry for the partial mixup/mistake on the functionality.

**Comment by jtsternberg** [comment]
To override how CMB2 sanitizes your data (and be able to do the sorting you want), you can use the `sanitization_cb` field parameter: https://github.com/CMB2/CMB2/wiki/Field-Parameters#sanitization_cb

Otherwise, you can use the `"cmb2_sanitize_{$field_type}"` filter to do the same thing after CMB2 does its own sanitization: 
https://github.com/CMB2/CMB2/blob/b59bb765c29d23622d11c09bfb5e696cd9fa2c12/includes/CMB2_Field.php#L507

**Comment by roscabgdn** [comment]
Thank you for your time and answers. I'll look into that.
