### ISSUE TITLE
Input type text_url doesn't fallback to HTTPS if HTTPS is allowed in Protocols option

### ISSUE THREAD

**Issue by james0r** [CMB2/CMB2#1391]
## Describe the bug
When using text_url with

`'protocols' => array('https', 'ftp', 'ftps', 'mailto', 'news', 'irc', 'gopher', 'nntp', 'feed', 'telnet' ), // Array of allowed protocols`

and an invalid URL is entered and saved, it just returns nothing to the display.

## Steps to reproduce (I have confirmed I can reproduce this issue on the [`develop`]
See above.

## Possible Solution
Have this field fallback to https (either higher in priority or lower than http. not sure the arguments for either)

## CMB2 Field Registration Code:

```php
$cmb_social_links->add_field([
    'name'       => __('Twitter URL', 'keystone'),
    'id'         => 'twitter',
    'type'       => 'text_url',
    'protocols' => array('https', 'ftp', 'ftps', 'mailto', 'news', 'irc', 'gopher', 'nntp', 'feed', 'telnet' ), // Array of allowed protocols
]);
```

## Your Environment
ClassicPress 1.2
Chrome 87

**Comment by tw2113** [comment]
Can't really claim this as a bug, since it's WordPress core's `esc_url_raw` function that gets used in this case. Closest I can find to provide a possible default for you would be filtering in something for the `clean_url` filter, if it gets to that point at least.

Alternatively, perhaps a front/js level validation for you before it lets you submit?

**Comment by tw2113** [comment]
Did you ever get a solution here @james0r

**Comment by james0r** [comment]
@tw2113 i just included http back in the allowed protocols. 

My issue didn't do a great job of documenting my steps either so now I have questions for my former self lol. Anyway we can close.
