### ISSUE TITLE
Repeatable Field Groups - File field

### ISSUE THREAD

**Issue by N-Molham** [CMB2/CMB2#178]
CMB2 version => `2.0.1`
WP version => `4.1`
Code => `example-functions.php`

Issue test-case :
1. Clean load of the page contains the repeatable group and doesn't have any entries.
3. before adding any new entries, select a file for the first ( default ) entry's file field, then remove the selection.
4. add new ( second ) entry.
5. select a file for the second entry's file field and it will change the first entry's file field instead !!!!
6. any other new entries added will work fine without that bug ... it only happens related to the first and second entries.

I hope I described the problem correctly.

**Comment by tw2113** [comment]
I'm going to close due to the age, some slight lack of detail for exactly which code snippet was used at the time, and the hope that it's been resolved since, or there are maybe other open issues with more detail/discussion going on that better highlight everything.

We can also always re-visit later with more detail if needed.
