### ISSUE TITLE
Theme check error - use of $method

### ISSUE THREAD

**Issue by gareth-gillman** [CMB2/CMB2#481]
Can't find anything on this on here, but when testing a theme with CMB2 as a required file (in the theme files) the following errors occur:

Found $method in file CMB2_Types.php.
Line 230: $concatenated_items .= $this->$method( $a, $i++ );

Found $method in file CMB2_Sanitize.php.
Line 387: $new_value[] = $this->$method( $val, true );

This is done when using http://themecheck.org/ - googling the warning (found method in cmb2_) shows lots of themes with the issue.

**Comment by tw2113** [comment]
This would be related to https://secure.php.net/manual/en/functions.variable-functions.php

I guess my biggest question is what specific reasons is this ThemeCheck website complaining about. Security issue? XSS? general bad PHP practice?

That said, I cant' find either of the original instances in trunk at the moment, so I'm curious if in the 3 years since the issue was created, we actually addressed it.

Closing for the time being.
