### ISSUE TITLE
default_cb is not called on group fields

### ISSUE THREAD

**Issue by rubengc** [CMB2/CMB2#972]
I found something strange where I am trying to get group fields working on widgets view

I tried to use default_cb for a group field but this callback is never used

Instead of use group field callback, CMB2 uses the default_cb in each field inside a group so with default_cb you only can set a default value of the first element

So, CMB2 should check if default ir a default_cb is present to execute It and initialize the group field value

**Comment by tw2113** [comment]
Hey @rubengc, can you start a support thread over at https://wordpress.org/support/plugin/cmb2 for this while we do initial testing/debugging? If we confirm it as a bug, we'll post a report here with as much info as we can manage at that time.

Also, when you start the thread, can you provide the configuration code you're using, so that we can try with matching code.

Thanks.

**Comment by rubengc** [comment]
Ping to @jtsternberg
